import { Car, CarType, DriverCarStatus } from "../types/CarDriverManagement";

export const carRawData: Car[] = [
  {
    id: "PTL.401",
    licensePlate: "กท79-0689",
    type: CarType.EightTon,
    status: DriverCarStatus.Ready,
  },
  {
    id: "PTL.402",
    licensePlate: "กท79-1245",
    type: CarType.TenTon,
    status: DriverCarStatus.NotReady,
    reason: "กำลังซ่อมเครื่องยนต์",
  },
  {
    id: "PTL.403",
    licensePlate: "กท79-5678",
    type: CarType.Trailer,
    status: DriverCarStatus.InProgress,
  },
  {
    id: "PTL.404",
    licensePlate: "กท79-9834",
    type: CarType.EightTon,
    status: DriverCarStatus.Ready,
  },
  {
    id: "PTL.405",
    licensePlate: "กท79-4521",
    type: CarType.TenTon,
    status: DriverCarStatus.Ready,
  },
  {
    id: "PTL.406",
    licensePlate: "กท79-7789",
    type: CarType.Trailer,
    status: DriverCarStatus.NotReady,
    reason: "คนขับลาป่วย",
  },
  {
    id: "PTL.407",
    licensePlate: "กท79-1134",
    type: CarType.EightTon,
    status: DriverCarStatus.InProgress,
  },
  {
    id: "PTL.408",
    licensePlate: "กท79-3345",
    type: CarType.TenTon,
    status: DriverCarStatus.Ready,
  },
  {
    id: "PTL.409",
    licensePlate: "กท79-9021",
    type: CarType.Trailer,
    status: DriverCarStatus.Ready,
  },
  {
    id: "PTL.410",
    licensePlate: "กท79-6654",
    type: CarType.EightTon,
    status: DriverCarStatus.NotReady,
    reason: "รอเปลี่ยนยาง",
  },
  {
    id: "PTL.411",
    licensePlate: "กท79-2398",
    type: CarType.TenTon,
    status: DriverCarStatus.InProgress,
  },
  {
    id: "PTL.412",
    licensePlate: "กท79-8741",
    type: CarType.Trailer,
    status: DriverCarStatus.Ready,
  },
  {
    id: "PTL.413",
    licensePlate: "กท79-1402",
    type: CarType.EightTon,
    status: DriverCarStatus.Ready,
  },
  {
    id: "PTL.414",
    licensePlate: "กท79-7850",
    type: CarType.TenTon,
    status: DriverCarStatus.NotReady,
    reason: "อยู่ระหว่างตรวจสภาพรถ",
  },
  {
    id: "PTL.415",
    licensePlate: "กท79-5544",
    type: CarType.Trailer,
    status: DriverCarStatus.Ready,
  },
  {
    id: "PTL.416",
    licensePlate: "กท79-3312",
    type: CarType.EightTon,
    status: DriverCarStatus.InProgress,
  },
  {
    id: "PTL.417",
    licensePlate: "กท79-6677",
    type: CarType.TenTon,
    status: DriverCarStatus.Ready,
  },
  {
    id: "PTL.418",
    licensePlate: "กท79-9088",
    type: CarType.Trailer,
    status: DriverCarStatus.NotReady,
    reason: "รอใบอนุญาตขนส่งสินค้าอันตราย",
  },
  {
    id: "PTL.419",
    licensePlate: "กท79-2234",
    type: CarType.EightTon,
    status: DriverCarStatus.Ready,
  },
  {
    id: "PTL.420",
    licensePlate: "กท79-9911",
    type: CarType.TenTon,
    status: DriverCarStatus.InProgress,
  },
];