import { CarType, DriverCarStatus } from "../types/CarDriver";
import { DeliveryStatus, Order, OrderStatus } from "../types/Order";

export const orderRawData: Order[] = [
  {
    car: {
      id: "PTL.401",
      licensePlate: "กท79-0689",
      type: CarType.EightTon,
      status: DriverCarStatus.Ready,
    },
    drivers: [
      {
        id: "1",
        name: "สมชาย ใจดี",
        tel: "081-852-3548",
        status: DriverCarStatus.Ready,
      },
      {
        id: "5",
        name: "สมปอง สุขใจ",
        tel: "081-234-5678",
        status: DriverCarStatus.Ready,
      },
    ],
    status: OrderStatus.InProgress,
    orderId: "45839PTL.221เที่ยว1",
    note: "โหลดไม่เกิน 85% / ชั่งปิดที่คลัง",
    currentLocation: "สระแก้ว",
    destination: "โรงบรรจุ สุขสวัสดิ์",
    loadGas: 10000,
    drop: 1,
    serveGas: 0,
    balanceGas: 10000,
    waitingLoadStatus: DeliveryStatus.Success,
    loadStatus: DeliveryStatus.InProgress,
    deliveryStatus: DeliveryStatus.Pending,
    serveStatus: DeliveryStatus.Pending,
    timeWaitingLoad: 30,
    timeLoad: 45,
    timeDelivery: 120,
    timeServe: 60,
    startTime: new Date("2025-09-12T08:00:00Z"),
    deadline: new Date("2025-09-12T14:30:00Z"),
  },
  {
    car: {
      id: "PTL.402",
      licensePlate: "กท79-1245",
      type: CarType.TenTon,
      status: DriverCarStatus.NotReady,
      reason: "กำลังซ่อมเครื่องยนต์",
    },
    drivers: [
      {
        id: "2",
        name: "มะเขือ เทศ",
        tel: "081-578-1235",
        status: DriverCarStatus.NotReady,
      },
    ],
    status: OrderStatus.Waiting,
    orderId: "45840PTL.222เที่ยว1",
    note: "ตรวจสอบสภาพรถก่อนเดินทาง",
    currentLocation: "-",
    destination: "โรงบรรจุ ปทุมธานี",
    loadGas: 0,
    drop: 0,
    serveGas: 0,
    balanceGas: 0,
    waitingLoadStatus: DeliveryStatus.Pending,
    loadStatus: DeliveryStatus.Pending,
    deliveryStatus: DeliveryStatus.Pending,
    serveStatus: DeliveryStatus.Pending,
    timeWaitingLoad: 0,
    timeLoad: 0,
    timeDelivery: 0,
    timeServe: 0,
    startTime: new Date("2025-09-13T07:30:00Z"),
    deadline: new Date("2025-09-13T09:00:00Z"),
  },
  {
    car: {
      id: "PTL.403",
      licensePlate: "กท79-5678",
      type: CarType.Trailer,
      status: DriverCarStatus.InProgress,
    },
    drivers: [
      {
        id: "6",
        name: "สมชาย ดีมาก",
        tel: "081-987-6543",
        status: DriverCarStatus.InProgress,
      },
      {
        id: "9",
        name: "มะเขือ เหลือง",
        tel: "081-666-9999",
        status: DriverCarStatus.InProgress,
        reason: "อยู่ระหว่างฝึกอบรม",
      },
    ],
    status: OrderStatus.InProgress,
    orderId: "45841PTL.223เที่ยว2",
    note: "ขนส่งด่วน กรุงเทพฯ → ระยอง",
    currentLocation: "ชลบุรี",
    destination: "โรงบรรจุ ระยอง",
    loadGas: 15000,
    drop: 2,
    serveGas: 5000,
    balanceGas: 10000,
    waitingLoadStatus: DeliveryStatus.Success,
    loadStatus: DeliveryStatus.Success,
    deliveryStatus: DeliveryStatus.InProgress,
    serveStatus: DeliveryStatus.Pending,
    timeWaitingLoad: 25,
    timeLoad: 60,
    timeDelivery: 180,
    timeServe: 90,
    startTime: new Date("2025-09-14T06:30:00Z"),
    deadline: new Date("2025-09-14T16:00:00Z"),
  },
];
