import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import { ToastProvider } from "../components/utils/ToastContext";

const notoSansThai = Noto_Sans_Thai({ subsets: ["thai"], display: "swap", variable: "--font-noto-sans-thai" })

export const metadata: Metadata = {
  title: "TMSG App",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className="h-full overflow-hidden">
        <Providers>
          <ToastProvider>
            {children}
          </ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
